config/routes.rb
Rails.application.routes.draw do
  root to: "games#index"
  resources :games
  get 'games/:id/play', to: 'games#play', as: 'play_game'
  get 'games/:id/play/:dice', to: 'games#play_dice', as: 'play_dice_game'
  resources :squares
end

app/models/game.rb
class Game < ActiveRecord::Base
  def json_positions
    JSON.parse(self.attributes["positions"] || [{"name" => "default", "val" => 1}])
  end

  def json_positions= json
    self.positions = json.to_json
  end

  def last_player
    self.json_positions
  end

  def nb_players
    self.json_positions.size
  end

  def player_name(offset=0)
    self.json_positions[(self.player + offset + self.nb_players) % self.nb_players]["name"]
  end
end

app/models/square.rb
class Square < ActiveRecord::Base

  default_scope -> {order(:position)}

  def self.max_position
    Square.order(:position).reverse.first.position
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :play, :play_dice]

  def play
  end

  def play_dice
    @dice = Integer(params[:dice])
    # forward, but cycle on the position maximum
    @square_pos = (@pos[@player]["val"] + @dice) % (Square.max_position + 1)
    @pos[@player]["val"] = @square_pos
    # select the first effect >= current position
    @effect = Square.order(:position).where("position >= ?", @square_pos).first unless @dice == 0
    # update position and set next player
    @game.update_attributes(
      player: (@player + 1) % @pos.size,
      positions: @pos.to_json
    )
    render :play
  end

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
    @pos = []
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
      @pos = @game.json_positions
      @player = @game.player.to_i
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:player, :positions)
    end
end

app/controllers/squares_controller.rb
class SquaresController < ApplicationController
  before_action :set_square, only: [:show, :edit, :update, :destroy]

  # GET /squares
  # GET /squares.json
  def index
    @squares = Square.all
  end

  # GET /squares/1
  # GET /squares/1.json
  def show
  end

  # GET /squares/new
  def new
    @square = Square.new
  end

  # GET /squares/1/edit
  def edit
  end

  # POST /squares
  # POST /squares.json
  def create
    @square = Square.new(square_params)

    respond_to do |format|
      if @square.save
        format.html { redirect_to @square, notice: 'Square was successfully created.' }
        format.json { render :show, status: :created, location: @square }
      else
        format.html { render :new }
        format.json { render json: @square.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /squares/1
  # PATCH/PUT /squares/1.json
  def update
    respond_to do |format|
      if @square.update(square_params)
        format.html { redirect_to @square, notice: 'Square was successfully updated.' }
        format.json { render :show, status: :ok, location: @square }
      else
        format.html { render :edit }
        format.json { render json: @square.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squares/1
  # DELETE /squares/1.json
  def destroy
    @square.destroy
    respond_to do |format|
      format.html { redirect_to squares_url, notice: 'Square was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_square
      @square = Square.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def square_params
      params.require(:square).permit(:position, :title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/views/games/_form.html.slim
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message

  .form-group
    .field
      = f.label :player
      = f.number_field :player, class: "form-control", placeholder: "player id (0 .. #{@pos.size-1})"
    .field
      = f.label :positions
      = f.text_area :positions, class: "form-control", placeholder: "positions"
  .actions = f.submit class: 'btn btn-success'

app/views/games/edit.html.slim
h1 Editing game

== render 'form'

= link_to 'Show', @game, class: 'btn'
= link_to 'Back', games_path, class: 'btn'

app/views/games/index.html.slim
h1 Listing games

table.table
  thead
    tr
      th Player
      th Names
      th
      //th
      //th

  tbody
    - @games.each do |game|
      tr
        td = (game.json_positions[game.player] || {"name" => ""})["name"]
        td = game.json_positions.map{|e| e["name"]}.join(", ")
        td
          = link_to 'Play', play_game_path(game), class: 'btn btn-success'
          = link_to 'Show', game, class: 'btn btn-primary'
          = link_to 'Edit', edit_game_path(game), class: 'btn btn-warning'
          = link_to 'Destroy', game, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger'

br

= link_to 'New Game', new_game_path, class: 'btn btn-primary'

app/views/games/new.html.slim
h1 New game

== render 'form'

= link_to 'Back', games_path, class: "btn"

app/views/games/play.html.slim
.container-fluid
  .row
    h3.page-header
      = @effect.title if @effect
      .small = "Last: " + @game.player_name(-1)
    - if @effect
      p = @effect.description

  .row
    h3.page-header = "Player #{@game.player} (#{@game.player_name})"


  .row
    .col-sm-offset-2.col-sm-8
      center
        samp = link_to " Pass ", play_dice_game_path(@game, 0), class: "btn btn-lg btn-default"

  - (0..4).each do |a|
    .row
      .col-sm-offset-2.col-sm-8
        center
          - (1..4).each do |b|
            - i = a * 4 + b
            - type = %w(danger warning default primary success)[a]
            samp = link_to "#{i}", play_dice_game_path(@game, i), class: "btn btn-lg btn-#{type} text-center", style: "margin: 2px; width: 80px; height: 80px; line-height: 40px; text-align: center;"

= link_to 'Back', games_path, class: 'btn'

app/views/games/show.html.slim
.row
  p
    strong.col-md-4 Player:
    .col-md-8 = @game.player
  p
    strong.col-md-4 Positions:
    .col-md-8 = @game.positions

= link_to 'Play', play_game_path(@game), class: 'btn btn-success'
= link_to 'Edit', edit_game_path(@game), class: 'btn'
= link_to 'Back', games_path, class: 'btn'

app/views/layouts/_infos.html.slim
#infos
  - if alert
    #alert.alert.bg-danger
      span.glyphicon.glyphicon-exclamation-sign aria-hidden="true"
      span.sr-only Error:
      = " #{alert}"
  - if notice
    #notice.alert.bg-warning
      span.glyphicon.glyphicon-info-sign aria-hidden="true"
      span.sr-only Error:
      = " #{notice}"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    #navbar-title.navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .navbar-brand
        = link_to "Destiny Game", "/games"

    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        li = link_to "Games", games_path
        li = link_to "Squares", squares_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title DestinyGame
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta charset="utf-8"
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]

  body
    = render partial: "/layouts/navbar"
    br

    .container-fluid
      .row
        #main.main
          = render partial: "/layouts/infos"
          #yield.yield
            = yield

app/views/squares/_form.html.slim
= form_for @square do |f|
  - if @square.errors.any?
    #error_explanation
      h2 = "#{pluralize(@square.errors.count, "error")} prohibited this square from being saved:"
      ul
        - @square.errors.full_messages.each do |message|
          li = message

  .form-group
    .field
      = f.label :position
      = f.number_field :position, class: "form-control", placeholder: "position"
    .field
      = f.label :title
      = f.text_field :title, class: "form-control", placeholder: "title"
    .field
      = f.label :description
      = f.text_area :description, class: "form-control", placeholder: "description"
    .field
      = f.label :image
      = f.text_field :image, class: "form-control", placeholder: "image"
  .actions = f.submit class: 'btn btn-success'

app/views/squares/edit.html.slim
h1 Editing square

== render 'form'

= link_to 'Show', @square, class: 'btn'
= link_to 'Back', squares_path, class: 'btn'

app/views/squares/index.html.slim
h1 Listing squares

table.table
  thead
    tr
      th Position
      th Title
      th Description
      //th Image
      th
      //th
      //th

  tbody
    - @squares.each do |square|
      tr
        td = square.position
        td = square.title
        td = square.description.to_s[0..30] + (square.description.to_s.size > 33 ? "..." : square.description.to_s[31..33].to_s)
        //td = square.image
        td
          = link_to 'Show', square, class: 'btn btn-primary'
          = link_to 'Edit', edit_square_path(square), class: 'btn btn-warning'
          = link_to 'Destroy', square, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger'

br

= link_to 'New Square', new_square_path, class: 'btn btn-primary'

app/views/squares/new.html.slim
h1 New square

== render 'form'

= link_to 'Back', squares_path, class: 'btn'

app/views/squares/show.html.slim
.row
  p
    strong.col-md-4 Position:
    .col-md-8 = @square.position
  p
    strong.col-md-4 Title:
    .col-md-8 = @square.title
  p
    strong.col-md-4 Description:
    .col-md-8 = @square.description
  p
    strong.col-md-4 Image:
    .col-md-8 = @square.image

= link_to 'Edit', edit_square_path(@square), class: 'btn'
= link_to 'Back', squares_path, class: 'btn'